In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('ejemplo_datos.csv')

In [ ]:
data.head()

  Nombre  Edad     Ciudad
0    Ana    23     Madrid
1   Luis    34  Barcelona
2  Pedro    45   Valencia
3  Marta    28    Sevilla
4  Sofía    32     Bilbao

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      object
 1   Edad    5 non-null      int64
 2   Ciudad  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [14]:
data.describe()

            Edad
count   5.000000
mean   32.400000
std     8.203658
min    23.000000
25%    28.000000
50%    32.000000
75%    34.000000
max    45.000000

In [ ]:
data.to_csv('nuevos_datos.csv')