In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([40, 50, 60, 70], index=['b', 'c', 'd', 'e'])

In [3]:
s1

a    10
b    20
c    30
dtype: int64

In [4]:
s2

b    40
c    50
d    60
e    70
dtype: int64

In [5]:
result = s1 + s2
print(result)

a     NaN
b    60.0
c    80.0
d     NaN
e     NaN
dtype: float64

In [7]:
result_con_fill = s1.add(s2, fill_value=0)
print(result_con_fill)

a    10.0
b    60.0
c    80.0
d    60.0
e    70.0
dtype: float64

In [8]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=[1, 2])
df2 = pd.DataFrame({'B': [5, 6], 'C': [7, 8]}, index=[2, 3])

In [9]:
df1

   A  B
1  1  3
2  2  4

In [10]:
df2

   B  C
2  5  7
3  6  8

In [11]:
resultado_df = df1 + df2
resultado_df

    A    B   C
1 NaN  NaN NaN
2 NaN  9.0 NaN
3 NaN  NaN NaN

In [12]:
resultado_df = df1.add(df2, fill_value=0)
resultado_df

     A    B    C
1  1.0  3.0  NaN
2  2.0  9.0  7.0
3  NaN  6.0  8.0